# Уровень логирования по умолчанию - WARN (скрывает INFO)
org.slf4j.simpleLogger.defaultLogLevel=WARN

# Уровень логирования для вашего пакета - WARN
org.slf4j.simpleLogger.log.org.nosulkora.postmaker=WARN

# Формат вывода
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS

# Показывать имя потока
org.slf4j.simpleLogger.showThreadName=false

# Показывать имя логгера
org.slf4j.simpleLogger.showLogName=false

# Показывать короткое имя логгера
org.slf4j.simpleLogger.showShortLogName=true

# Уровень логирования для SQL запросов
org.slf4j.simpleLogger.log.org.nosulkora.postmaker.repository=WARN

# Уровень для ConnectionManager
org.slf4j.simpleLogger.log.org.nosulkora.postmaker.repository.ConnectionManager=WARN